# Global settings for dev environment
global:
  environment: dev
  argocd:
    namespace: argocd

# Individual application definitions
applications:
  database:
    enabled: true
    name: database-app-dev
    component: database
    environment: dev
    project: default
    source:
      repoURL: https://github.com/CHARANPRAJWAL/ArgoCD-Multicluster-Deployments.git
      targetRevision: main
      path: k8s-manifests/database
    destination:
      server: https://kubernetes.default.svc
      namespace: voting-app-dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true

  redis:
    enabled: true
    name: redis-app-dev
    component: redis
    environment: dev
    project: default
    source:
      repoURL: https://github.com/CHARANPRAJWAL/ArgoCD-Multicluster-Deployments.git
      targetRevision: main
      path: k8s-manifests/redis
    destination:
      server: https://kubernetes.default.svc
      namespace: voting-app-dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true

  vote:
    enabled: true
    name: vote-app-dev
    component: vote
    environment: dev
    project: default
    source:
      repoURL: https://github.com/CHARANPRAJWAL/ArgoCD-Multicluster-Deployments.git
      targetRevision: main
      path: k8s-manifests/vote
    destination:
      server: https://kubernetes.default.svc
      namespace: voting-app-dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true

  result:
    enabled: true
    name: result-app-dev
    component: result
    environment: dev
    project: default
    source:
      repoURL: https://github.com/CHARANPRAJWAL/ArgoCD-Multicluster-Deployments.git
      targetRevision: main
      path: k8s-manifests/result
    destination:
      server: https://kubernetes.default.svc
      namespace: voting-app-dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true

  worker:
    enabled: true
    name: worker-app-dev
    component: worker
    environment: dev
    project: default
    source:
      repoURL: https://github.com/CHARANPRAJWAL/ArgoCD-Multicluster-Deployments.git
      targetRevision: main
      path: k8s-manifests/worker
    destination:
      server: https://kubernetes.default.svc
      namespace: voting-app-dev
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true 