apiVersion: v1
kind: ServiceAccount
metadata:
  name: argocd-app
  namespace: voting-app-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-app-role
  namespace: voting-app-dev
rules:
  - apiGroups: ["", "apps", "extensions"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-app-binding
  namespace: voting-app-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-app-role
subjects:
  - kind: ServiceAccount
    name: argocd-app
    namespace: voting-app-dev 