apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-root-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CHARANPRAJWAL/ArgoCD-Multicluster-Deployments.git
    targetRevision: develop
    path: .
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: voting-app-dev
  syncPolicy:
    automated: {} 