{{- if and .Values.applications (hasKey .Values.applications "rootProd") }}
{{- if .Values.applications.rootProd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-root-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/CHARANPRAJWAL/ArgoCD-Multicluster-Deployments.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://10.201.1.105:6443
    namespace: voting-app-prod
  syncPolicy:
    automated: {}
{{- end }}
{{- end }} 